"""Add expanded profile fields to candidate profile

Revision ID: 0edab2fd2d02
Revises: 95c11d28f286
Create Date: 2026-05-23 13:33:25.843183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0edab2fd2d02'
down_revision: Union[str, Sequence[str], None] = '95c11d28f286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the Enum type manually for Postgres
    job_mode_enum = postgresql.ENUM('REMOTE', 'ONSITE', 'HYBRID', 'ANY', name='jobmode')
    job_mode_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('current_designation', sa.String(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('desired_role', sa.String(), nullable=True))
    
    # Add as nullable first
    op.add_column('candidate_profiles', sa.Column('job_mode', sa.Enum('REMOTE', 'ONSITE', 'HYBRID', 'ANY', name='jobmode'), nullable=True))
    
    # Update existing rows
    op.execute("UPDATE candidate_profiles SET job_mode = 'ANY' WHERE job_mode IS NULL")
    
    # Set to NOT NULL
    op.alter_column('candidate_profiles', 'job_mode', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'job_mode')
    op.drop_column('candidate_profiles', 'desired_role')
    op.drop_column('candidate_profiles', 'current_designation')
    # ### end Alembic commands ###

    # Drop the Enum type manually for Postgres
    job_mode_enum = postgresql.ENUM('REMOTE', 'ONSITE', 'HYBRID', 'ANY', name='jobmode')
    job_mode_enum.drop(op.get_bind())
