"""Add expanded fields to Job model

Revision ID: 9866a4afeacc
Revises: fc57127e3b92
Create Date: 2026-05-23 17:43:33.960310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9866a4afeacc'
down_revision: Union[str, Sequence[str], None] = 'fc57127e3b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('organization_name', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('role', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('work_mode', sa.Enum('REMOTE', 'ONSITE', 'HYBRID', 'ANY', name='jobmode'), nullable=True))
    op.add_column('jobs', sa.Column('location', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('salary_range', sa.String(), nullable=True))

    # Populate existing data
    op.execute("UPDATE jobs SET organization_name = 'Unknown', role = 'Not Specified', work_mode = 'ANY', location = 'Remote' WHERE organization_name IS NULL")

    # Set to NOT NULL
    op.alter_column('jobs', 'organization_name', nullable=False)
    op.alter_column('jobs', 'role', nullable=False)
    op.alter_column('jobs', 'work_mode', nullable=False)
    op.alter_column('jobs', 'location', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'salary_range')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'work_mode')
    op.drop_column('jobs', 'role')
    op.drop_column('jobs', 'organization_name')
    # ### end Alembic commands ###
