"""Simplify candidate profile fields

Revision ID: fc57127e3b92
Revises: 0edab2fd2d02
Create Date: 2026-05-23 16:05:40.490438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc57127e3b92'
down_revision: Union[str, Sequence[str], None] = '0edab2fd2d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'experience')
    op.drop_column('candidate_profiles', 'education')
    op.drop_column('candidate_profiles', 'mobile_no')
    op.drop_column('candidate_profiles', 'current_designation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('current_designation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('candidate_profiles', sa.Column('mobile_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('candidate_profiles', sa.Column('education', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('candidate_profiles', sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
